[project]
name = "bcn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "confluent-kafka>=2.6.0",
    "google-cloud-bigquery[pandas]>=3.26.0",
    "ipykernel>=6.29.5",
    "pandas-gbq>=0.24.0",
]
